name: your_project_name
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"  # Adjust this based on your Dart SDK version

  # Firebase dependencies
dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.24.2  # Latest stable version
  firebase_auth: ^4.17.3  # Add this if using authentication


  # Other dependencies can be added here
  # http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Add development dependencies here, e.g.:
  # pedantic: ^1.11.0

flutter:
  uses-material-design: true

  # To add assets to your application, uncomment and modify the assets section:
  # assets:
  #   - assets/images/
  #   - assets/icons/

  # To add custom fonts, uncomment and modify the fonts section:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
